apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hria.name" . }}-api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: { app.kubernetes.io/name: hria, app.kubernetes.io/component: api }
